bot:
  token: token
  guildId: 0
  icon_url: https://localhost/icon.png
  embedFooter: Developed by Xen0Xys
  activity:
    enable: true
    # Can be PLAYING, STREAMING, LISTENING or WATCHING
    type: PLAYING
    text: V1.0 DEV
    # Only for streaming
    url: null

mysql:
  enable: false
  host: 0.0.0.0
  port: 3306
  user: username
  password: password
  database: database_name

modules:
  deadlines:
    enable: true
    expiryDelay: 5 # The delay in minutes before an unannounced deadline (caused by a bug) will not be announced with mention
  timetable:
    enable: true
    url: https://localhost?edt=edt