bot:
  token: token
  guildId: 0
  icon_url: https://localhost/icon.png

edt:
  url: https://localhost?edt=edt

mysql:
  enable: false
  host: 0.0.0.0
  port: 3306
  user: username
  password: password
  database: database_name